name = "vtex"
type = "cli"

[resolve]
git-url = "https://github.com/vtex/toolbelt"

[platform.linux]
download-file = "v{version}.tar.gz"

[platform.macos]
download-file = "v{version}.tar.gz"

[platform.windows]
download-file = "v{version}.zip"

[install]
download-url = "https://github.com/vtex/toolbelt/archive/refs/tags/{download_file}"

[install.arch]
x86 = "i686"
